 <h1 style="color: red">Numpy for Beginners</h1>

In [2]:
import numpy as np  #Import numpy

In [3]:
array = np.array([[1,2,3],[4,5,6]])  #Create a two-dimensional array

In [4]:
print(array)
print('Dim', array.ndim)
print('Shape', array.shape)
print('Size', array.size)

[[1 2 3]
 [4 5 6]]
Dim 2
Shape (2, 3)
Size 6


In [5]:
a = np.array([1,2,3,4,5])
b = np.arange(2,14,2).reshape((2,3))#Create an array from two to twelve, not included, with step of two
                                    #.reshape() reshape the array for 1*6 to 2*3
print(b)
c = np.zeros(6) #Create an array with six floating 0.
print('\n')
print(c)
print(c.dtype)
d = np.ones(6, dtype = np.int) #Create an array with six integer 1.
print('\n')
print(d)
print(d.dtype)
e = np.random.random((2,3)) #Create an 2*3 array with elements that are randomly picked between 0 to 1.
print('\n')
print(e)
f = b-a
print('\n')
print(f)

print(a,b,c,d,e,f, sep='\n')
print(f<-9)
print(f==5)

[[ 2  4  6]
 [ 8 10 12]]


[ 0.  0.  0.  0.  0.  0.]
float64


[1 1 1 1 1 1]
int32


[[ 0.19063916  0.89962152  0.98998715]
 [ 0.67746338  0.51319666  0.03126831]]




NameError: name 'f' is not defined

In [ ]:
a = np.array([[3,6,9],[12,15,18]])
print(a)
print(np.sum(a))
print(np.sum(a, axis=1)) #add all elements on the basis of row
print(np.sum(a, axis=0)) #add all elements on the basis of column

In [ ]:
a = np.array([[2,4,6],[8,10,12]])
b = np.arange(6).reshape((2,3))
print(a,b,a-b,a*b, sep='\n') #* is normal multiplication
print('\n')
print(b.T) #transpose
print(np.dot(a,b.T)) # This is array multiplication

In [ ]:
#Merge
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B))) #vertical merge
print(np.hstack((A,B))) #horizontal merge

In [ ]:
#Split
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #Vertically split the array into 3 new arrays
print(np.hsplit(a,2)) #Horizontally split the array into 2 new arrays

<h1 style="color: red">Pandas for Beginners</h1>

<h3 style="color:blue">Series</h3>

In [25]:
import pandas as pd
s = pd.Series([1,'abc','6',np.nan,44,1])
a = np.array([1,'abc','6',np.nan,44,1])

print(s)
print(a)

0      1
1    abc
2      6
3    NaN
4     44
5      1
dtype: object
['1' 'abc' '6' 'nan' '44' '1']


 <h3 style="color: blue">DataFrame</h3> 

In [26]:
#Method one: use array to create DataFrame
print(np.random.random()) # np.random.random returns random floats in the half-open interval [0 1)
print(np.random.randn()) # np.random.randn returns random floats sampled from a univariate nomal distribution


df = pd.DataFrame(np.random.randn(7,3))
print(df)

0.5270674051654711
0.4877522776344939
          0         1         2
0  0.304530 -0.505199 -2.178460
1 -0.602826 -2.148203 -0.128477
2  0.508710 -0.515343  0.162402
3  0.045451 -2.130113  0.412960
4  1.127601 -0.337147 -2.118635
5  1.893130 -1.494616  0.817288
6  0.475257 -0.042919 -2.253243


In [43]:
#Method one: use array to create DataFrame
eat = np.random.randint(10, size=(7,3))*5+50
print(eat)
dates = pd.date_range('20170812', periods=7)
print(dates)
#print(np.dtype(dates))
df0 = pd.DataFrame(eat)
print(df0)
df1 = pd.DataFrame(eat, index=dates, columns=['Breakfast', 'Lunch', 'Dinner'])
print(df1)

[[75 50 50]
 [55 70 75]
 [65 85 85]
 [55 80 55]
 [70 90 80]
 [55 95 75]
 [70 75 60]]
DatetimeIndex(['2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15',
               '2017-08-16', '2017-08-17', '2017-08-18'],
              dtype='datetime64[ns]', freq='D')
    0   1   2
0  75  50  50
1  55  70  75
2  65  85  85
3  55  80  55
4  70  90  80
5  55  95  75
6  70  75  60
            Breakfast  Lunch  Dinner
2017-08-12         75     50      50
2017-08-13         55     70      75
2017-08-14         65     85      85
2017-08-15         55     80      55
2017-08-16         70     90      80
2017-08-17         55     95      75
2017-08-18         70     75      60


In [83]:
#Method two: use dictionary to create DataFrame
df2 = pd.DataFrame({'Decimal': pd.Series([1,3,6,4], index=list(range(4)), dtype='float32'),
                   'Integer': np.array([3]*4, dtype='int32'),
                   'Time': pd.Timestamp('20170812'),
                   'Category': pd.Categorical(['test','train','test','train'])})
x = pd.Series(1,index=list(range(4)), dtype='float32')
#print(x)
y = np.array([3]*4, dtype='int32')
#print(y)
z = pd.Timestamp('20170816')
#print(z)
k = pd.Categorical(['test','train','test','train'])
#print(k)
#print(df2)
#print(df2.dtypes)
#print(df2.index)
#print(df2.columns)
#print(df2.values)
#print(df2.T)
print(df2.sort_index(axis=1,ascending=False)) #axis=1 takes columns as sorting index
print(df2.sort_values(by='Decimal'))

        Time  Integer  Decimal Category
0 2017-08-12        3      1.0     test
1 2017-08-12        3      3.0    train
2 2017-08-12        3      6.0     test
3 2017-08-12        3      4.0    train
  Category  Decimal  Integer       Time
0     test      1.0        3 2017-08-12
1    train      3.0        3 2017-08-12
3    train      4.0        3 2017-08-12
2     test      6.0        3 2017-08-12


In [89]:
# Pandas: Selecting data
print(df1)
print('\n')
print(df1['Lunch'])
print('\n')
print(df1[0:3])

            Breakfast  Lunch  Dinner
2017-08-12         75     50      50
2017-08-13         55     70      75
2017-08-14         65     85      85
2017-08-15         55     80      55
2017-08-16         70     90      80
2017-08-17         55     95      75
2017-08-18         70     75      60


2017-08-12    50
2017-08-13    70
2017-08-14    85
2017-08-15    80
2017-08-16    90
2017-08-17    95
2017-08-18    75
Freq: D, Name: Lunch, dtype: int32


            Breakfast  Lunch  Dinner
2017-08-12         75     50      50
2017-08-13         55     70      75
2017-08-14         65     85      85


In [132]:
print(df1)
# Pandas: Selecting data by label (refer to the label and not the position)
print(df1.loc['20170812'])
print(df1.loc['20170813':'20170816',['Breakfast','Lunch']])
print('\n')
# Pandas: Selecting data by position
print(df1.iloc[3,1])
print(df1.iloc[3:5,1:3])
print('\n')
# Pandas: Selecting data by ix
print(df1.ix[:3,['Lunch','Dinner']])

            Breakfast  Lunch  Dinner
2017-08-12         75   50.0      50
2017-08-13         55   70.0      75
2017-08-14         65    NaN      40
2017-08-15         55   80.0      55
2017-08-16         70   90.0      40
2017-08-17         55   95.0      40
2017-08-18         70   75.0      60
Breakfast    75.0
Lunch        50.0
Dinner       50.0
Name: 2017-08-12 00:00:00, dtype: float64
            Breakfast  Lunch
2017-08-13         55   70.0
2017-08-14         65    NaN
2017-08-15         55   80.0
2017-08-16         70   90.0


80.0
            Lunch  Dinner
2017-08-15   80.0      55
2017-08-16   90.0      40


            Lunch  Dinner
2017-08-12   50.0      50
2017-08-13   70.0      75
2017-08-14    NaN      40


In [111]:
# Pandas: Conditional expression
print(df1[df1.Lunch > 80])

            Breakfast  Lunch  Dinner
2017-08-14         65     85      85
2017-08-16         70     90      80
2017-08-17         55     95      75


In [140]:
# Pandas: Re-assign data
#df1.Dinner[df1.Lunch>80]=40  --> this method Pandas would select df1.Dinner first, and then returns
#a DataFrame that is singly-indexed. Then, another python operation df1_dinner[df1.Lunch>80] will
#happens. THis is because pandas sees these operations as separate events.
df1.loc[:,['Dinner']][df1.Lunch>80] = 40
print(df1[df1.Lunch>80])
df1.loc['20170814','Lunch'] = np.nan
print(df1)
print(df1.dtypes)

            Breakfast  Lunch  Dinner
2017-08-16       70.0   90.0      40
2017-08-17       55.0   95.0      40
            Breakfast  Lunch  Dinner
2017-08-12       75.0   50.0      50
2017-08-13       55.0   70.0      75
2017-08-14       65.0    NaN      40
2017-08-15        NaN   80.0      55
2017-08-16       70.0   90.0      40
2017-08-17       55.0   95.0      40
2017-08-18       70.0   75.0      60
Breakfast    float64
Lunch        float64
Dinner         int32
dtype: object


In [130]:
# Pandas: Dealing with missing values
print(df1.isnull())
df1.isnull().sum()

            Breakfast  Lunch  Dinner
2017-08-12      False  False   False
2017-08-13      False  False   False
2017-08-14      False   True   False
2017-08-15      False  False   False
2017-08-16      False  False   False
2017-08-17      False  False   False
2017-08-18      False  False   False


Breakfast    0
Lunch        1
Dinner       0
dtype: int64

In [131]:
# Panadas: Dealing with missing values --> replace them with 0
df1.fillna(value=0)

Breakfast  Lunch  Dinner
2017-08-12         75   50.0      50
2017-08-13         55   70.0      75
2017-08-14         65    0.0      40
2017-08-15         55   80.0      55
2017-08-16         70   90.0      40
2017-08-17         55   95.0      40
2017-08-18         70   75.0      60

In [146]:
# Panadas: Dealing with missing values --> erase the missing values
print(df1)
df1.dropna(
    axis=0,    #0: operates under the base of row; 1: operates under the base of column
    how='any'  #'any':Drop the whole row or column if there is any NaN value.
               #'all':Drop the whole row or column if the values in the row or column are all NaN.
)

            Breakfast  Lunch  Dinner
2017-08-12       75.0   50.0      50
2017-08-13       55.0   70.0      75
2017-08-14       65.0    NaN      40
2017-08-15        NaN   80.0      55
2017-08-16       70.0   90.0      40
2017-08-17       55.0   95.0      40
2017-08-18       70.0   75.0      60


Breakfast  Lunch  Dinner
2017-08-12       75.0   50.0      50
2017-08-13       55.0   70.0      75
2017-08-16       70.0   90.0      40
2017-08-17       55.0   95.0      40
2017-08-18       70.0   75.0      60

In [155]:
# Pandas: Other usages
print(df1)
df1.dropna(thresh=3)  #Keep only the rows with at least 3 non-na values
df1.dropna(subset=['Breakfast']) #Only drops the rows or columns in the subset that have NaN value.

            Breakfast  Lunch  Dinner
2017-08-12       75.0   50.0      50
2017-08-13       55.0   70.0      75
2017-08-14       65.0    NaN      40
2017-08-15        NaN   80.0      55
2017-08-16       70.0   90.0      40
2017-08-17       55.0   95.0      40
2017-08-18       70.0   75.0      60


Breakfast  Lunch  Dinner
2017-08-12       75.0   50.0      50
2017-08-13       55.0   70.0      75
2017-08-14       65.0    NaN      40
2017-08-16       70.0   90.0      40
2017-08-17       55.0   95.0      40
2017-08-18       70.0   75.0      60