 <h1 style="color: red">Numpy for Beginners</h1>

In [1]:
import numpy as np  #Import numpy

In [2]:
array = np.array([[1,2,3],[4,5,6]])  #Create a two-dimensional array

In [3]:
print(array)
print('Dim', array.ndim)
print('Shape', array.shape)
print('Size', array.size)

[[1 2 3]
 [4 5 6]]
Dim 2
Shape (2, 3)
Size 6


In [33]:
a = np.array([1,2,3,4,5])
b = np.arange(2,14,2).reshape((2,3))#Create an array from two to twelve, not included, with step of two
                                    #.reshape() reshape the array for 1*6 to 2*3
print(b)
c = np.zeros(6) #Create an array with six floating 0.
print('\n')
print(c)
print(c.dtype)
d = np.ones(6, dtype = np.int) #Create an array with six integer 1.
print('\n')
print(d)
print(d.dtype)
e = np.random.random((2,3)) #Create an 2*3 array with elements that are randomly picked between 0 to 1.
print('\n')
print(e)
#f = b-a
print('\n')
print(f)

print(a,b,c,d,e,f, sep='\n')
print(f<-9)
print(f==5)

[[ 2  4  6]
 [ 8 10 12]]


[ 0.  0.  0.  0.  0.  0.]
float64


[1 1 1 1 1 1]
int32


[[ 0.35480782  0.0642445   0.20831242]
 [ 0.6983032   0.79724555  0.58232503]]


[1 2 3 4 5]
[1 2 3 4 5]
[[ 2  4  6]
 [ 8 10 12]]
[ 0.  0.  0.  0.  0.  0.]
[1 1 1 1 1 1]
[[ 0.35480782  0.0642445   0.20831242]
 [ 0.6983032   0.79724555  0.58232503]]
[1 2 3 4 5]
[False False False False False]
[False False False False  True]


In [36]:
a = np.array([[3,6,9],[12,15,18]])
print(a)
print(np.sum(a))
print(np.sum(a, axis=1)) #add all elements on the basis of row
print(np.sum(a, axis=0)) #add all elements on the basis of column

[[ 3  6  9]
 [12 15 18]]
63
[18 45]
[15 21 27]


In [44]:
a = np.array([[2,4,6],[8,10,12]])
b = np.arange(6).reshape((2,3))
print(a,b,a-b,a*b, sep='\n') #* is normal multiplication
print('\n')
print(b.T) #transpose
print(np.dot(a,b.T)) # This is array multiplication

[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[ 0  4 12]
 [24 40 60]]


[[0 3]
 [1 4]
 [2 5]]
[[ 16  52]
 [ 34 124]]


In [46]:
#Merge
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B))) #vertical merge
print(np.hstack((A,B))) #horizontal merge

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [47]:
#Split
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #Vertically split the array into 3 new arrays
print(np.hsplit(a,2)) #Horizontally split the array into 2 new arrays

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
