 <h1 style="color: red">Numpy for Beginners</h1>

In [32]:
import numpy as np  #Import numpy

In [33]:
array = np.array([[1,2,3],[4,5,6]])  #Create a two-dimensional array

In [34]:
print(array)
print('Dim', array.ndim)
print('Shape', array.shape)
print('Size', array.size)

[[1 2 3]
 [4 5 6]]
Dim 2
Shape (2, 3)
Size 6


In [35]:
a = np.array([1,2,3,4,5])
b = np.arange(2,14,2).reshape((2,3))#Create an array from two to twelve, not included, with step of two
                                    #.reshape() reshape the array for 1*6 to 2*3
print(a)
print(b)
c = np.zeros(6) #Create an array with six floating 0.
print('\n')
print(c)
print(c.dtype)
d = np.ones(6, dtype = np.int) #Create an array with six integer 1.
print('\n')
print(d)
print(d.dtype)
e = np.random.random((2,3)) #Create an 2*3 array with elements that are randomly picked between 0 to 1.
print('\n')
print(e)
#f = b-a
print('\n')
# print(f)

print(a,b,c,d,e,sep='\n')
# print(a,b,c,d,e,f, sep='\n')
#print(f<-9)
#print(f==5)

[1 2 3 4 5]
[[ 2  4  6]
 [ 8 10 12]]


[ 0.  0.  0.  0.  0.  0.]
float64


[1 1 1 1 1 1]
int32


[[ 0.84093311  0.00798526  0.29544894]
 [ 0.79051128  0.45105444  0.63603064]]


[1 2 3 4 5]
[[ 2  4  6]
 [ 8 10 12]]
[ 0.  0.  0.  0.  0.  0.]
[1 1 1 1 1 1]
[[ 0.84093311  0.00798526  0.29544894]
 [ 0.79051128  0.45105444  0.63603064]]


In [36]:
a = np.array([[3,6,9],[12,15,18]])
print(a)
print(np.sum(a))
print(np.sum(a, axis=1)) #add all elements on the basis of row
print(np.sum(a, axis=0)) #add all elements on the basis of column

[[ 3  6  9]
 [12 15 18]]
63
[18 45]
[15 21 27]


In [37]:
a = np.array([[2,4,6],[8,10,12]])
b = np.arange(6).reshape((2,3))
print(a,b,a-b,a*b, sep='\n') #* is normal multiplication
print('\n')
print(b.T) #transpose
print(np.dot(a,b.T)) # This is array multiplication

[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[ 0  4 12]
 [24 40 60]]


[[0 3]
 [1 4]
 [2 5]]
[[ 16  52]
 [ 34 124]]


In [38]:
#Merge
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B))) #vertical merge
print(np.hstack((A,B))) #horizontal merge

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [39]:
#Split
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #Vertically split the array into 3 new arrays
print(np.hsplit(a,2)) #Horizontally split the array into 2 new arrays

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


<h1 style="color: red">Pandas for Beginners</h1>

<h3 style="color:blue">Series</h3>

In [40]:
import pandas as pd
s = pd.Series([1,'abc','6',np.nan,44,1])
a = np.array([1,'abc','6',np.nan,44,1])
# print(t)
print(s)
print(a)

0      1
1    abc
2      6
3    NaN
4     44
5      1
dtype: object
['1' 'abc' '6' 'nan' '44' '1']


 <h3 style="color: blue">DataFrame</h3> 

In [41]:
#Method one: use array to create DataFrame
print(np.random.random()) # np.random.random returns random floats in the half-open interval [0 1)
print(np.random.randn()) # np.random.randn returns random floats sampled from a univariate nomal distribution


df = pd.DataFrame(np.random.randn(7,3))
print(df)

0.9253412435708225
-0.45691043204688636
          0         1         2
0  0.797731 -0.027400  0.217731
1 -0.388598 -0.977950 -0.395518
2 -1.130482  0.714348 -0.099555
3 -0.037650  0.056500 -0.023990
4 -1.165988  0.747042  0.655972
5  0.051600  0.166281  0.700247
6 -0.985070  0.331307  1.667151


In [42]:
#Method one: use array to create DataFrame
eat = np.random.randint(10, size=(7,3))*5+50
print(eat)
dates = pd.date_range('20170812', periods=7)
print(dates)
# print(np.dtype(dates))
df0 = pd.DataFrame(eat)
print(df0)
df1 = pd.DataFrame(eat, index=dates, columns=['Breakfast', 'Lunch', 'Dinner'])
print(df1)

[[90 60 80]
 [80 50 80]
 [60 90 80]
 [95 50 55]
 [85 85 85]
 [50 90 85]
 [55 65 80]]
DatetimeIndex(['2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15',
               '2017-08-16', '2017-08-17', '2017-08-18'],
              dtype='datetime64[ns]', freq='D')
    0   1   2
0  90  60  80
1  80  50  80
2  60  90  80
3  95  50  55
4  85  85  85
5  50  90  85
6  55  65  80
            Breakfast  Lunch  Dinner
2017-08-12         90     60      80
2017-08-13         80     50      80
2017-08-14         60     90      80
2017-08-15         95     50      55
2017-08-16         85     85      85
2017-08-17         50     90      85
2017-08-18         55     65      80


In [43]:
#Method two: use dictionary to create DataFrame
df2 = pd.DataFrame({'Decimal': pd.Series([1,3,6,4], index=list(range(4)), dtype='float32'),
                   'Integer': np.array([3]*4, dtype='int32'),
                   'Time': pd.Timestamp('20170812'),
                   'Category': pd.Categorical(['test','train','test','train'])})
x = pd.Series(1,index=list(range(4)), dtype='float32')
# print(x)
y = np.array([3]*4, dtype='int32')
#print(y)
z = pd.Timestamp('20170816')
#print(z)
k = pd.Categorical(['test','train','test','train'])
# print(k)
print(df2)
#print(df2.dtypes)
#print(df2.index)
#print(df2.columns)
#print(df2.values)
#print(df2.T)
print(df2.sort_index(axis=1,ascending=False)) #axis=1 takes columns as sorting index
print(df2.sort_values(by='Decimal'))

  Category  Decimal  Integer       Time
0     test      1.0        3 2017-08-12
1    train      3.0        3 2017-08-12
2     test      6.0        3 2017-08-12
3    train      4.0        3 2017-08-12
        Time  Integer  Decimal Category
0 2017-08-12        3      1.0     test
1 2017-08-12        3      3.0    train
2 2017-08-12        3      6.0     test
3 2017-08-12        3      4.0    train
  Category  Decimal  Integer       Time
0     test      1.0        3 2017-08-12
1    train      3.0        3 2017-08-12
3    train      4.0        3 2017-08-12
2     test      6.0        3 2017-08-12


In [44]:
# Pandas: Selecting data
print(df1)
print('\n')
print(df1['Lunch'])
print('\n')
print(df1[0:3])

            Breakfast  Lunch  Dinner
2017-08-12         90     60      80
2017-08-13         80     50      80
2017-08-14         60     90      80
2017-08-15         95     50      55
2017-08-16         85     85      85
2017-08-17         50     90      85
2017-08-18         55     65      80


2017-08-12    60
2017-08-13    50
2017-08-14    90
2017-08-15    50
2017-08-16    85
2017-08-17    90
2017-08-18    65
Freq: D, Name: Lunch, dtype: int32


            Breakfast  Lunch  Dinner
2017-08-12         90     60      80
2017-08-13         80     50      80
2017-08-14         60     90      80


In [45]:
print(df1)
# Pandas: Selecting data by label (refer to the label and not the position)
print(df1.loc['20170812'])
print(df1.loc['20170813':'20170816',['Breakfast','Lunch']])
print('\n')
# Pandas: Selecting data by position
print(df1.iloc[3,1])
print(df1.iloc[3:5,1:3])
print('\n')
# Pandas: Selecting data by ix
print(df1.ix[:3,['Lunch','Dinner']])

            Breakfast  Lunch  Dinner
2017-08-12         90     60      80
2017-08-13         80     50      80
2017-08-14         60     90      80
2017-08-15         95     50      55
2017-08-16         85     85      85
2017-08-17         50     90      85
2017-08-18         55     65      80
Breakfast    90
Lunch        60
Dinner       80
Name: 2017-08-12 00:00:00, dtype: int32
            Breakfast  Lunch
2017-08-13         80     50
2017-08-14         60     90
2017-08-15         95     50
2017-08-16         85     85


50
            Lunch  Dinner
2017-08-15     50      55
2017-08-16     85      85


            Lunch  Dinner
2017-08-12     60      80
2017-08-13     50      80
2017-08-14     90      80


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  # This is added back by InteractiveShellApp.init_path()


In [46]:
# Pandas: Conditional expression
print(df1[df1.Lunch > 80])

            Breakfast  Lunch  Dinner
2017-08-14         60     90      80
2017-08-16         85     85      85
2017-08-17         50     90      85


In [47]:
# Pandas: Re-assign data
#df1.Dinner[df1.Lunch>80]=40  --> this method Pandas would select df1.Dinner first, and then returns
#a DataFrame that is singly-indexed. Then, another python operation df1_dinner[df1.Lunch>80] will
#happens. THis is because pandas sees these operations as separate events.
df1.loc[:,['Dinner']][df1.Lunch>80] = 40
print(df1[df1.Lunch>80])
df1.loc['20170814','Lunch'] = np.nan
print(df1)
print(df1.dtypes)

            Breakfast  Lunch  Dinner
2017-08-14         60     90      80
2017-08-16         85     85      85
2017-08-17         50     90      85
            Breakfast  Lunch  Dinner
2017-08-12         90   60.0      80
2017-08-13         80   50.0      80
2017-08-14         60    NaN      80
2017-08-15         95   50.0      55
2017-08-16         85   85.0      85
2017-08-17         50   90.0      85
2017-08-18         55   65.0      80
Breakfast      int32
Lunch        float64
Dinner         int32
dtype: object


In [48]:
# Pandas: Dealing with missing values
print(df1.isnull())
df1.isnull().sum()

            Breakfast  Lunch  Dinner
2017-08-12      False  False   False
2017-08-13      False  False   False
2017-08-14      False   True   False
2017-08-15      False  False   False
2017-08-16      False  False   False
2017-08-17      False  False   False
2017-08-18      False  False   False


Breakfast    0
Lunch        1
Dinner       0
dtype: int64

In [49]:
# Panadas: Dealing with missing values --> replace them with 0
df1.fillna(value=0)

Breakfast  Lunch  Dinner
2017-08-12         90   60.0      80
2017-08-13         80   50.0      80
2017-08-14         60    0.0      80
2017-08-15         95   50.0      55
2017-08-16         85   85.0      85
2017-08-17         50   90.0      85
2017-08-18         55   65.0      80

In [50]:
# Panadas: Dealing with missing values --> erase the missing values
print(df1)
df1.dropna(
    axis=0,    #0: operates under the base of row; 1: operates under the base of column
    how='any'  #'any':Drop the whole row or column if there is any NaN value.
               #'all':Drop the whole row or column if the values in the row or column are all NaN.
)

            Breakfast  Lunch  Dinner
2017-08-12         90   60.0      80
2017-08-13         80   50.0      80
2017-08-14         60    NaN      80
2017-08-15         95   50.0      55
2017-08-16         85   85.0      85
2017-08-17         50   90.0      85
2017-08-18         55   65.0      80


Breakfast  Lunch  Dinner
2017-08-12         90   60.0      80
2017-08-13         80   50.0      80
2017-08-15         95   50.0      55
2017-08-16         85   85.0      85
2017-08-17         50   90.0      85
2017-08-18         55   65.0      80

In [51]:
# Pandas: Other usages
print(df1)
df1.dropna(thresh=3)  #Keep only the rows with at least 3 non-na values
df1.dropna(subset=['Breakfast']) #Only drops the rows or columns in the subset that have NaN value.

            Breakfast  Lunch  Dinner
2017-08-12         90   60.0      80
2017-08-13         80   50.0      80
2017-08-14         60    NaN      80
2017-08-15         95   50.0      55
2017-08-16         85   85.0      85
2017-08-17         50   90.0      85
2017-08-18         55   65.0      80


Breakfast  Lunch  Dinner
2017-08-12         90   60.0      80
2017-08-13         80   50.0      80
2017-08-14         60    NaN      80
2017-08-15         95   50.0      55
2017-08-16         85   85.0      85
2017-08-17         50   90.0      85
2017-08-18         55   65.0      80

In [52]:
# Pandas: Dealing with missing values --> interpolation
from sklearn.preprocessing import Imputer
# print(df1.dtypes)
print(df1.values)
print(df1.values.dtype)
# print(df1.values.dtypes)
imr = Imputer(missing_values='NaN', strategy='mean', axis=0) #axis = 0 for columns, axis = 1 for rows
imr_2 = Imputer(missing_values='NaN', strategy='mean', axis=0)
imr = imr.fit(df1)
imputed_data = imr.transform(df1.values)
imputed_data_2 = imr_2.fit_transform(df1) #fit + transform
print(imputed_data)
print(imputed_data_2)


[[ 90.  60.  80.]
 [ 80.  50.  80.]
 [ 60.  nan  80.]
 [ 95.  50.  55.]
 [ 85.  85.  85.]
 [ 50.  90.  85.]
 [ 55.  65.  80.]]
float64
[[ 90.          60.          80.        ]
 [ 80.          50.          80.        ]
 [ 60.          66.66666667  80.        ]
 [ 95.          50.          55.        ]
 [ 85.          85.          85.        ]
 [ 50.          90.          85.        ]
 [ 55.          65.          80.        ]]
[[ 90.          60.          80.        ]
 [ 80.          50.          80.        ]
 [ 60.          66.66666667  80.        ]
 [ 95.          50.          55.        ]
 [ 85.          85.          85.        ]
 [ 50.          90.          85.        ]
 [ 55.          65.          80.        ]]


In [53]:
# Pandas: load file

#load csv file
data = pd.read_csv('nescsv2.csv')
print(data)
data = data.T
print(data)
data.to_csv('nescsv2_transpose.csv')


FileNotFoundError: File b'nescsv2.csv' does not exist

In [75]:
# Pandas concat DataFrame

#concat

df1_concat = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2_concat = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3_concat = pd.DataFrame(np.ones((3,4))*2, columns=['a','b','c','d'])
# print(df1_concat, df2_concat, df3_concat,sep='\n')
res = pd.concat([df1_concat, df2_concat, df3_concat], axis = 0, ignore_index = True)
# print('\n')
print(res)
# print('\n')
print(df1_concat.columns)
print(df1_concat.index)

#join: {'inner', 'outer'}
df4_concat = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'],index=[1,2,3])
df5_concat = pd.DataFrame(np.ones((3,4))*1, columns=['b','c','d','e'],index=[2,3,4])
res_outer = pd.concat([df4_concat, df5_concat], axis=0, join='outer', ignore_index=False) #join default is outer
res_inner = pd.concat([df4_concat, df5_concat], axis=0, join='inner', ignore_index=False)

print(res_outer)

res_reset = res_inner.reset_index(drop=True)
print(list(res_reset.columns)) # Same as print(list(res_reset))
print(res_reset)
print(res_reset.groupby(['b','c']))
print(res_reset.groupby(['b','c']).groups)
print(res_reset.groupby(['b','c']).groups.values())
# print(res_outer, res_inner, sep='\n')
# print(diff_inner_outer)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0
Index(['a', 'b', 'c', 'd'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0
['b', 'c', 'd']
     b    c    d
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0
5  1.0  1.0  1.0
{(0.0, 0.0): Int64Index([0, 1, 2], dtype='int64'), (1.0, 1.0): Int64Index([3, 4, 5], dtype='int64')}
dict_values([Int64Index([0, 1, 2], dtype='int64'), Int64Index([3, 4, 5], dtype='int64')])


<h4 style='color: blue'>Pandas append DataFrame</h4>
<span>DataFrame.<b>append</b>(other, ignore_index=False, verify_integrity=False)</span>
<br>
<p>Append rows of <i>other</i> to the end of this frame, returning a new object. Columns not in this frame are added as new columns</p>

In [55]:
df1_test = pd.DataFrame({
    'Date': pd.Timestamp('20170812'),
    'Fruit': ['Banana', 'Orange', 'Apple', 'Celery'],
    'Num': [22.1,8.6,7.6,10.2],
    'Color': ['Yello', 'Orange', 'Green', 'Green']
})

df2_test = pd.DataFrame({
    'Fruit': ['Banana', 'Orange', 'Apple', 'Celery', 'Apple', 'Orange'],
    'Num': [22.1, 8.6, 7.6, 10.2, 22.1, 8.6],
    'Color': ['Yellow','Orange','Green','Green','Red','Orange']
})

dates_test = []
for i in range(1,7):
    if i <=4:
        dates_test.append(pd.Timestamp('20170812'))
    else:
        dates_test.append(pd.Timestamp('20170813')) 

df2_test.insert(0, 'Date', dates_test)
# print(dates_test)
print(df2_test)
print(df1_test)

df_merge_test = pd.concat([df1_test, df2_test])
print(df_merge_test)

df_merge_test = df_merge_test.reset_index(drop = True) #pd.concat([df1_test, df2_test], ignore_index=True) could get the same effect
print(df_merge_test)

print (list(df_merge_test)) #Same as list(df_merge_test.columns) 
df_gpby = df_merge_test.groupby(list(df_merge_test))
# print(df_gpby.groups)
print(df_gpby.groups.values())
# print(df_gpby.count())

# for x in df_gpby.groups.values():
#     print(x)
idx = [x[0] for x in df_gpby.groups.values() if len(x) == 1]
print(idx)

df_merge_test.reindex(idx)

        Date   Color   Fruit   Num
0 2017-08-12  Yellow  Banana  22.1
1 2017-08-12  Orange  Orange   8.6
2 2017-08-12   Green   Apple   7.6
3 2017-08-12   Green  Celery  10.2
4 2017-08-13     Red   Apple  22.1
5 2017-08-13  Orange  Orange   8.6
    Color       Date   Fruit   Num
0   Yello 2017-08-12  Banana  22.1
1  Orange 2017-08-12  Orange   8.6
2   Green 2017-08-12   Apple   7.6
3   Green 2017-08-12  Celery  10.2
    Color       Date   Fruit   Num
0   Yello 2017-08-12  Banana  22.1
1  Orange 2017-08-12  Orange   8.6
2   Green 2017-08-12   Apple   7.6
3   Green 2017-08-12  Celery  10.2
0  Yellow 2017-08-12  Banana  22.1
1  Orange 2017-08-12  Orange   8.6
2   Green 2017-08-12   Apple   7.6
3   Green 2017-08-12  Celery  10.2
4     Red 2017-08-13   Apple  22.1
5  Orange 2017-08-13  Orange   8.6
    Color       Date   Fruit   Num
0   Yello 2017-08-12  Banana  22.1
1  Orange 2017-08-12  Orange   8.6
2   Green 2017-08-12   Apple   7.6
3   Green 2017-08-12  Celery  10.2
4  Yellow 2017-08-12

Color       Date   Fruit   Num
9  Orange 2017-08-13  Orange   8.6
8     Red 2017-08-13   Apple  22.1
0   Yello 2017-08-12  Banana  22.1
4  Yellow 2017-08-12  Banana  22.1