 <h1 style="color: red">Numpy for Beginners</h1>

In [22]:
import numpy as np  #Import numpy

In [23]:
array = np.array([[1,2,3],[4,5,6]])  #Create a two-dimensional array

In [24]:
print(array)
print('Dim', array.ndim)
print('Shape', array.shape)
print('Size', array.size)

[[1 2 3]
 [4 5 6]]
Dim 2
Shape (2, 3)
Size 6


In [25]:
a = np.array([1,2,3,4,5])
b = np.arange(2,14,2).reshape((2,3))#Create an array from two to twelve, not included, with step of two
                                    #.reshape() reshape the array for 1*6 to 2*3
print(a)
print(b)
c = np.zeros(6) #Create an array with six floating 0.
print('\n')
print(c)
print(c.dtype)
d = np.ones(6, dtype = np.int) #Create an array with six integer 1.
print('\n')
print(d)
print(d.dtype)
e = np.random.random((2,3)) #Create an 2*3 array with elements that are randomly picked between 0 to 1.
print('\n')
print(e)
#f = b-a
print('\n')
# print(f)

print(a,b,c,d,e,sep='\n')
# print(a,b,c,d,e,f, sep='\n')
#print(f<-9)
#print(f==5)

[1 2 3 4 5]
[[ 2  4  6]
 [ 8 10 12]]


[ 0.  0.  0.  0.  0.  0.]
float64


[1 1 1 1 1 1]
int32


[[ 0.05219362  0.90341796  0.06470964]
 [ 0.57908224  0.77183944  0.71899757]]


[1 2 3 4 5]
[[ 2  4  6]
 [ 8 10 12]]
[ 0.  0.  0.  0.  0.  0.]
[1 1 1 1 1 1]
[[ 0.05219362  0.90341796  0.06470964]
 [ 0.57908224  0.77183944  0.71899757]]


In [26]:
a = np.array([[3,6,9],[12,15,18]])
print(a)
print(np.sum(a))
print(np.sum(a, axis=1)) #add all elements on the basis of row
print(np.sum(a, axis=0)) #add all elements on the basis of column

[[ 3  6  9]
 [12 15 18]]
63
[18 45]
[15 21 27]


In [27]:
a = np.array([[2,4,6],[8,10,12]])
b = np.arange(6).reshape((2,3))
print(a,b,a-b,a*b, sep='\n') #* is normal multiplication
print('\n')
print(b.T) #transpose
print(np.dot(a,b.T)) # This is array multiplication

[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]
[[ 0  4 12]
 [24 40 60]]


[[0 3]
 [1 4]
 [2 5]]
[[ 16  52]
 [ 34 124]]


In [28]:
#Merge
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B))) #vertical merge
print(np.hstack((A,B))) #horizontal merge

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [29]:
#Split
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #Vertically split the array into 3 new arrays
print(np.hsplit(a,2)) #Horizontally split the array into 2 new arrays

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


<h1 style="color: red">Pandas for Beginners</h1>

<h3 style="color:blue">Series</h3>

In [30]:
import pandas as pd
s = pd.Series([1,'abc','6',np.nan,44,1])
a = np.array([1,'abc','6',np.nan,44,1])

print(s)
print(a)

0      1
1    abc
2      6
3    NaN
4     44
5      1
dtype: object
['1' 'abc' '6' 'nan' '44' '1']


 <h3 style="color: blue">DataFrame</h3> 

In [31]:
#Method one: use array to create DataFrame
print(np.random.random()) # np.random.random returns random floats in the half-open interval [0 1)
print(np.random.randn()) # np.random.randn returns random floats sampled from a univariate nomal distribution


df = pd.DataFrame(np.random.randn(7,3))
print(df)

0.7683985016289315
-1.743970053890798
          0         1         2
0 -1.530666  0.912511  1.463592
1  0.441934 -0.605598  1.658580
2 -0.435810 -1.479400  0.037328
3  0.126506 -0.205712 -0.938709
4 -0.813361  0.196704  0.380190
5  0.090246 -1.285109  1.028883
6 -0.736495  0.243148  0.542910


In [32]:
#Method one: use array to create DataFrame
eat = np.random.randint(10, size=(7,3))*5+50
print(eat)
dates = pd.date_range('20170812', periods=7)
print(dates)
#print(np.dtype(dates))
df0 = pd.DataFrame(eat)
print(df0)
df1 = pd.DataFrame(eat, index=dates, columns=['Breakfast', 'Lunch', 'Dinner'])
print(df1)

[[65 90 80]
 [75 70 70]
 [65 70 90]
 [55 75 75]
 [60 50 90]
 [55 65 50]
 [75 80 90]]
DatetimeIndex(['2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15',
               '2017-08-16', '2017-08-17', '2017-08-18'],
              dtype='datetime64[ns]', freq='D')
    0   1   2
0  65  90  80
1  75  70  70
2  65  70  90
3  55  75  75
4  60  50  90
5  55  65  50
6  75  80  90
            Breakfast  Lunch  Dinner
2017-08-12         65     90      80
2017-08-13         75     70      70
2017-08-14         65     70      90
2017-08-15         55     75      75
2017-08-16         60     50      90
2017-08-17         55     65      50
2017-08-18         75     80      90


In [33]:
#Method two: use dictionary to create DataFrame
df2 = pd.DataFrame({'Decimal': pd.Series([1,3,6,4], index=list(range(4)), dtype='float32'),
                   'Integer': np.array([3]*4, dtype='int32'),
                   'Time': pd.Timestamp('20170812'),
                   'Category': pd.Categorical(['test','train','test','train'])})
x = pd.Series(1,index=list(range(4)), dtype='float32')
#print(x)
y = np.array([3]*4, dtype='int32')
#print(y)
z = pd.Timestamp('20170816')
#print(z)
k = pd.Categorical(['test','train','test','train'])
#print(k)
#print(df2)
#print(df2.dtypes)
#print(df2.index)
#print(df2.columns)
#print(df2.values)
#print(df2.T)
print(df2.sort_index(axis=1,ascending=False)) #axis=1 takes columns as sorting index
print(df2.sort_values(by='Decimal'))

        Time  Integer  Decimal Category
0 2017-08-12        3      1.0     test
1 2017-08-12        3      3.0    train
2 2017-08-12        3      6.0     test
3 2017-08-12        3      4.0    train
  Category  Decimal  Integer       Time
0     test      1.0        3 2017-08-12
1    train      3.0        3 2017-08-12
3    train      4.0        3 2017-08-12
2     test      6.0        3 2017-08-12


In [34]:
# Pandas: Selecting data
print(df1)
print('\n')
print(df1['Lunch'])
print('\n')
print(df1[0:3])

            Breakfast  Lunch  Dinner
2017-08-12         65     90      80
2017-08-13         75     70      70
2017-08-14         65     70      90
2017-08-15         55     75      75
2017-08-16         60     50      90
2017-08-17         55     65      50
2017-08-18         75     80      90


2017-08-12    90
2017-08-13    70
2017-08-14    70
2017-08-15    75
2017-08-16    50
2017-08-17    65
2017-08-18    80
Freq: D, Name: Lunch, dtype: int32


            Breakfast  Lunch  Dinner
2017-08-12         65     90      80
2017-08-13         75     70      70
2017-08-14         65     70      90


In [35]:
print(df1)
# Pandas: Selecting data by label (refer to the label and not the position)
print(df1.loc['20170812'])
print(df1.loc['20170813':'20170816',['Breakfast','Lunch']])
print('\n')
# Pandas: Selecting data by position
print(df1.iloc[3,1])
print(df1.iloc[3:5,1:3])
print('\n')
# Pandas: Selecting data by ix
print(df1.ix[:3,['Lunch','Dinner']])

            Breakfast  Lunch  Dinner
2017-08-12         65     90      80
2017-08-13         75     70      70
2017-08-14         65     70      90
2017-08-15         55     75      75
2017-08-16         60     50      90
2017-08-17         55     65      50
2017-08-18         75     80      90
Breakfast    65
Lunch        90
Dinner       80
Name: 2017-08-12 00:00:00, dtype: int32
            Breakfast  Lunch
2017-08-13         75     70
2017-08-14         65     70
2017-08-15         55     75
2017-08-16         60     50


75
            Lunch  Dinner
2017-08-15     75      75
2017-08-16     50      90


            Lunch  Dinner
2017-08-12     90      80
2017-08-13     70      70
2017-08-14     70      90


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  # This is added back by InteractiveShellApp.init_path()


In [36]:
# Pandas: Conditional expression
print(df1[df1.Lunch > 80])

            Breakfast  Lunch  Dinner
2017-08-12         65     90      80


In [37]:
# Pandas: Re-assign data
#df1.Dinner[df1.Lunch>80]=40  --> this method Pandas would select df1.Dinner first, and then returns
#a DataFrame that is singly-indexed. Then, another python operation df1_dinner[df1.Lunch>80] will
#happens. THis is because pandas sees these operations as separate events.
df1.loc[:,['Dinner']][df1.Lunch>80] = 40
print(df1[df1.Lunch>80])
df1.loc['20170814','Lunch'] = np.nan
print(df1)
print(df1.dtypes)

            Breakfast  Lunch  Dinner
2017-08-12         65     90      80
            Breakfast  Lunch  Dinner
2017-08-12         65   90.0      80
2017-08-13         75   70.0      70
2017-08-14         65    NaN      90
2017-08-15         55   75.0      75
2017-08-16         60   50.0      90
2017-08-17         55   65.0      50
2017-08-18         75   80.0      90
Breakfast      int32
Lunch        float64
Dinner         int32
dtype: object


In [38]:
# Pandas: Dealing with missing values
print(df1.isnull())
df1.isnull().sum()

            Breakfast  Lunch  Dinner
2017-08-12      False  False   False
2017-08-13      False  False   False
2017-08-14      False   True   False
2017-08-15      False  False   False
2017-08-16      False  False   False
2017-08-17      False  False   False
2017-08-18      False  False   False


Breakfast    0
Lunch        1
Dinner       0
dtype: int64

In [39]:
# Panadas: Dealing with missing values --> replace them with 0
df1.fillna(value=0)

Breakfast  Lunch  Dinner
2017-08-12         65   90.0      80
2017-08-13         75   70.0      70
2017-08-14         65    0.0      90
2017-08-15         55   75.0      75
2017-08-16         60   50.0      90
2017-08-17         55   65.0      50
2017-08-18         75   80.0      90

In [40]:
# Panadas: Dealing with missing values --> erase the missing values
print(df1)
df1.dropna(
    axis=0,    #0: operates under the base of row; 1: operates under the base of column
    how='any'  #'any':Drop the whole row or column if there is any NaN value.
               #'all':Drop the whole row or column if the values in the row or column are all NaN.
)

            Breakfast  Lunch  Dinner
2017-08-12         65   90.0      80
2017-08-13         75   70.0      70
2017-08-14         65    NaN      90
2017-08-15         55   75.0      75
2017-08-16         60   50.0      90
2017-08-17         55   65.0      50
2017-08-18         75   80.0      90


Breakfast  Lunch  Dinner
2017-08-12         65   90.0      80
2017-08-13         75   70.0      70
2017-08-15         55   75.0      75
2017-08-16         60   50.0      90
2017-08-17         55   65.0      50
2017-08-18         75   80.0      90

In [41]:
# Pandas: Other usages
print(df1)
df1.dropna(thresh=3)  #Keep only the rows with at least 3 non-na values
df1.dropna(subset=['Breakfast']) #Only drops the rows or columns in the subset that have NaN value.

            Breakfast  Lunch  Dinner
2017-08-12         65   90.0      80
2017-08-13         75   70.0      70
2017-08-14         65    NaN      90
2017-08-15         55   75.0      75
2017-08-16         60   50.0      90
2017-08-17         55   65.0      50
2017-08-18         75   80.0      90


Breakfast  Lunch  Dinner
2017-08-12         65   90.0      80
2017-08-13         75   70.0      70
2017-08-14         65    NaN      90
2017-08-15         55   75.0      75
2017-08-16         60   50.0      90
2017-08-17         55   65.0      50
2017-08-18         75   80.0      90

In [54]:
# Pandas: Dealing with missing values --> interpolation
from sklearn.preprocessing import Imputer
print(df1.dtypes)
print(df1.values)
print(df1.values.dtype)
# print(df1.values.dtypes)
imr = Imputer(missing_values='NaN', strategy='mean', axis=0)
imr = imr.fit(df1)
imputed_data = imr.transform(df1.values)
imputed_data


Breakfast      int32
Lunch        float64
Dinner         int32
dtype: object
[[ 65.  90.  80.]
 [ 75.  70.  70.]
 [ 65.  nan  90.]
 [ 55.  75.  75.]
 [ 60.  50.  90.]
 [ 55.  65.  50.]
 [ 75.  80.  90.]]
float64


array([[ 65.        ,  90.        ,  80.        ],
       [ 75.        ,  70.        ,  70.        ],
       [ 65.        ,  71.66666667,  90.        ],
       [ 55.        ,  75.        ,  75.        ],
       [ 60.        ,  50.        ,  90.        ],
       [ 55.        ,  65.        ,  50.        ],
       [ 75.        ,  80.        ,  90.        ]])